name: Run VeloceReduction_tutorial.py with 001122 upon Pull Request

on:
  pull_request:
    types: [opened, synchronize] 

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'  # This is the version that I used on 20 Dec 2024.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy astropy matplotlib

      - name: Run Python script
        run: python ./VeloceReduction_tutorial.py
